# only for local testing. This starts all containers necessary for llm-server to run
version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - /tmp/qdrant_storage:/qdrant/storage
    networks:
      - openchat_network

networks:
  openchat_network: